name: screenshot-tool
version: '1.0.0'
summary: Create simple and beautiful presentations on the Linux desktop
description: |
  screenshot-tool is a modern and intuitive desktop presentation app based
  upon SpiceOfDesign's presentation concept. Built from the ground up
  for elementary OS, it gives you everything you need to create simple
  and beautiful presentations.

grade: stable
confinement: strict

plugs:
  elementary-platform-loki:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: elementary-platform-loki:elementary-platform-loki

slots:
  screenshot-tool:
    interface: dbus
    bus: session
    name: io.elementary.screenshot-tool

apps:
  screenshot-tool:
    command: desktop-launch $SNAP/usr/bin/io.elementary.screenshot-tool
    plugs:
      - x11
      - unity7
      - home
      - gsettings
      - pulseaudio
      - opengl
      - network

parts:
  elementary:
    plugin: nil
    prepare: |
      add-apt-repository -y ppa:elementary-os/stable
      add-apt-repository -y ppa:elementary-os/os-patches
      echo "Package: *" > /etc/apt/preferences.d/elementary-stable
      echo "Pin: release o=LP-PPA-elementary-os-stable" >> /etc/apt/preferences.d/elementary-stable
      echo "Pin-Priority: 1000" >> /etc/apt/preferences.d/elementary-stable
      echo "Package: *" > /etc/apt/preferences.d/elementary-patches
      echo "Pin: release o=LP-PPA-elementary-os-os-patches" >> /etc/apt/preferences.d/elementary-patches
      echo "Pin-Priority: 1000" >> /etc/apt/preferences.d/elementary-patches
      apt update
      apt dist-upgrade -y
  screenshot-tool:
    build-attributes: [no-system-libraries]
    after: [elementary, desktop-gnome-platform]
    plugin: meson
    meson-parameters: [--prefix=/usr]
    source: .
    build-packages:
      - build-essential
      - desktop-file-utils
      - gettext
      - libcanberra-dev
      - libgee-0.8-dev
      - libgtk-3-dev
      - valac
      - libgranite-dev
      - libjson-glib-dev
      - libgudev-1.0-dev
      - libevdev-dev
    organize:
      share/glib-2.0: usr/share/glib-2.0

